-- Database Schema for Zouma Gift Shop (Supabase/PostgreSQL)

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: clients
CREATE TABLE IF NOT EXISTS clients (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  phone TEXT,
  phone2 TEXT,
  address TEXT,
  client_code TEXT UNIQUE,
  dob DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: products
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  serial SERIAL UNIQUE,
  name TEXT NOT NULL,
  wholesale_price NUMERIC(12, 2) DEFAULT 0,
  selling_price NUMERIC(12, 2) DEFAULT 0,
  stock INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: orders
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
 status TEXT CHECK (status IN ('NEW', 'PREPARING', 'READY', 'DELIVERED')),
  date DATE NOT NULL,
  discount_percentage NUMERIC(5, 2) DEFAULT 0,
  paid_amount NUMERIC(12, 2) DEFAULT 0,
  total NUMERIC(12, 2) DEFAULT 0,
  cost NUMERIC(12, 2) DEFAULT 0,
  profit NUMERIC(12, 2) DEFAULT 0,
  discount NUMERIC(12, 2) DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: order_items
CREATE TABLE IF NOT EXISTS order_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  price NUMERIC(12, 2) NOT NULL,
  qty INT NOT NULL CHECK (qty > 0)
);

-- Table: users
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'employee' CHECK (role IN ('super_admin', 'employee')),
  permissions TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert a default super_admin account for initial setup
-- Password is 'admin123' (will be hashed in the app backend, but for reference:
-- Bcrypt hash with salt rounds 10 for 'admin123' can be generated by script.
-- Example hash: $2a$10$Wpkyg043mC66A4T.v17m1ugkP6a5P0O9Sskp6kIieQy/Q0U5L0s0K )
INSERT INTO users (name, email, password_hash, role, permissions)
VALUES (
  'Super Admin',
  'admin@zouma.com',
  '$2a$10$Wpkyg043mC66A4T.v17m1ugkP6a5P0O9Sskp6kIieQy/Q0U5L0s0K', -- hash of admin123
  'super_admin',
  ARRAY['dashboard', 'clients', 'orders', 'products', 'profits', 'users']
) ON CONFLICT (email) DO NOTHING;
